# Code generated by kubecon-pr-generator. DO NOT EDIT.
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Name }}
spec:
  forProvider:
    location: {{ .Region | toGCPRegion }}
  providerConfigRef:
    name: default
