# Code generated by kubecon-pr-generator. DO NOT EDIT.
resources:{{ if not .ResourceTypes }} []{{ end }}
{{- range .ResourceTypes }}
- {{ . }}.yaml
{{- end }}

namePrefix: "{{ .CloudProvider }}-{{ .AccountID }}-{{ .RegionCode }}"
