name: Golang Check

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - edited
    - synchronize
    - reopened

env:
  GOLANGCI_VERSION: "1.64.8"

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Run tests
      run: go test ./...
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v${{ env.GOLANGCI_VERSION }}
        args: --timeout=5m --config=.golangci.yaml --new --fix
